# idiomas.py

_idioma_atual = "pt"

def set_idioma(sigla):
    global _idioma_atual
    _idioma_atual = sigla

def tr(chave):
    """Retorna o texto no idioma atual. Se não achar, retorna a própria chave."""
    return _DICIONARIO.get(_idioma_atual, {}).get(chave, chave)

_DICIONARIO = {
    "pt": {
        "btn_tutorial": "📚 Como Usar",
        "btn_config": "⚙️ Configurações / Licença",
        "btn_novidades": "📋 Novidades",
        "btn_avisos": "📢 Avisos",
        "btn_buscando": "⏳ Buscando...",
        "nov_janela": "📋 Novidades - VegaSlides ({})",
        "nov_header": "<b>O que há de novo na versão {}:</b>",
        "nov_btn_ok": "Entendi",
        "msg_update_titulo": "🚀 Aplicativo Atualizado ({})!",
        "msg_update_texto": "<b>O VegaSlides foi atualizado para a versão {}!</b><br><br>Clique no botão '📋 Novidades' no topo da tela para ver todos os detalhes das melhorias baixadas diretamente do servidor.",
        "msg_update_vazio": "Sem novidades registradas para esta versão no servidor.",
        "msg_update_erro_api": "Não foi possível resgatar as novidades do servidor no momento.",
        "msg_update_erro_con": "Falha de conexão com a Nave-Mãe:\n{}",
        "btn_load": "1. Carregar Apresentação Pronta (.pptx)",
        "lbl_pptx_vazio": "Nenhum arquivo selecionado",
        "lbl_titulo_ia": "🧠 Motor de Criação por Inteligência Artificial:",
        "txt_tema_placeholder": "Digite o tema para a IA criar a apresentação do zero...",
        "btn_ia": "Criar Apresentação\nAutomática (IA)",
        "btn_historico": "🕒 Recuperar\nSalvo",
        "lbl_presets": "✨ Formatações Prontas (Presets):",
        "lbl_cor_titulos": "2. Cor dos Títulos:",
        "btn_cor_titulos_btn": "🎨 Cor dos Títulos",
        "lbl_cor_textos": "2.1. Cor dos Textos:",
        "btn_cor_textos_btn": "🎨 Cor dos Textos (Corpo/Cards)",
        "btn_add_font": "➕ Nova Fonte",
        "lbl_fonte_titulos": "📝 Fonte dos Títulos:",
        "lbl_fonte_textos": "📝 Fonte dos Textos:",
        "btn_fill_color": "3. Escolher Cor de Fundo dos Cards (Opcional)",
        "btn_bg": "4. Fundo do Slide (Opcional)",
        "lbl_bg_preview": "Sem imagem",
        "chk_scale": "5. Escala das imagens:",
        "chk_text_scale": "5.1. Aumentar textos em:",
        "lbl_preview_text_title": "Título Exemplo",
        "lbl_preview_text_body": "Este é o corpo do texto.<br>Veja como ele cresce e muda.",
        "chk_notes": "5.2. Inserir Roteiro do Apresentador nas anotações nativas",
        "chk_barra_lateral": "5.3. Exibir barra azul lateral",
        "btn_save": "6. Processar Apresentação e Salvar",
        "btn_pdf": "7. Converter o PPTX atual para PDF",
        "txt_tema_lock": "🔒 Geração Inteligente bloqueada (Licença FREE). Clique aqui para assinar.",
        
        "cfg_title": "⚙️ Configurações do App",
        "cfg_tab_lic": "Licença",
        "cfg_tab_ia": "Inteligência Artificial",
        "cfg_tab_vis": "Aparência",
        "cfg_lbl_lic": "<b>💳 GESTÃO DE PLANOS E ASSINATURAS</b><br><br>Selecione a licença desejada abaixo para liberar a geração de apresentações. O plano <b>SAAS ELITE</b> desbloqueia a Inteligência Artificial da Cloudflare, enquanto o <b>SAAS Padrão</b> usa o Google Gemini.<br><br><i>(Escolha o plano e clique em Salvar para abrir a loja)</i>",
        "cfg_status_lic": "<b>Status da Licença atual:</b>",
        "cfg_lbl_idioma": "Idioma / Language:",
        "cfg_lbl_tema": "Tema do Aplicativo:",
        "cfg_lbl_zoom": "🔎 Zoom da Tela (Acessibilidade):",
        "cfg_btn_salvar": "Salvar Configurações",
        "cfg_btn_buscar": "🔄 Buscar Modelos",
        "cfg_btn_load_cf": "🔄 Carregar CF",
        "cfg_aviso_saas": "✅ <b>Licença SaaS Ativa</b>\nO motor principal está liberado.",
        "cfg_chk_gemini": "🔵 Usar Google Gemini (Padrão)",
        "cfg_lbl_key_gemini": "Chave de API Gemini (BYOK):",
        "cfg_lbl_modelo": "Modelo:",
        "cfg_chk_cf": "🟠 Usar Cloudflare Workers AI",
        "cfg_btn_upgrade": "⭐ Upgrade ELITE",
        "cfg_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "cfg_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        
        "tema_escuro": "Escuro",
        "tema_claro": "Claro",
        "lic_free": "FREE (Edição Manual)",
        "lic_byok": "BYOK (Sua Chave)",
        "lic_saas": "SAAS (Chave Embutida)",
        "font_default": "Padrão do Tema",
        "preset_manual": "Personalizado (Manual)",
        "preset_corp": "Corporativo Azul",
        "preset_dark": "Dark Mode Clássico",
        "preset_clean": "Minimalista Clean",
        "ia_saas_active": "✅ <b>Licença SaaS Ativa</b>\nO motor principal está liberado.",
        "ia_chk_gemini": "🔵 Usar Google Gemini (Padrão)",
        "ia_chk_cf": "🟠 Usar Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Chave de API Gemini (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Modelo:",
        "btn_upgrade_elite": "⭐ Upgrade ELITE",
        
        "loja_titulo": "🛒 Loja VegaTech - VegaSlides",
        "loja_loading": "⏳ A carregar planos disponíveis...",
        "loja_cupom": "Tem um cupom de desconto? (Opcional)",
        "loja_escolha": "Escolha o Pacote Ideal para Você:",
        "loja_btn_assinar": "ASSINAR AGORA",
        "loja_vazio": "Nenhum plano configurado no Master.",
        "loja_gerando": "A gerar ambiente seguro de pagamento...",
        
        "tut_btn_sair": "❌ Sair do Tutorial",
        "tut_btn_prox": "Entendi, Próximo ➔",
        "tut_btn_fim": "Concluir Tutorial ✔️",
        "tut_p1_tit": "Passo 1: O Motor e a Licença",
        "tut_p1_txt": "Aqui você configura sua chave de API (BYOK) ou ativa seu plano SAAS. Sem isso, a Inteligência Artificial não funciona!",
        "tut_p1b_tit": "Passo 1.1: O Editor de Apresentação",
        "tut_p1b_txt": "Ainda dentro das Configurações, na aba 'Editor', você pode definir se o app deve abrir o PowerPoint ou algum outro programa, automaticamente no final ou apenas revelar a pasta salva para você.",
        "tut_p2_tit": "Passo 2: Fique Atualizado",
        "tut_p2_txt": "Sempre que o app atualizar, clique aqui para ver o que mudou e quais novos recursos foram adicionados diretamente pelo servidor.",
        "tut_p3_tit": "Passo 3: Edição Manual",
        "tut_p3_txt": "Se você já tem uma apresentação pronta e quer apenas usar o nosso aplicativo para aplicar um design ou converter em PDF, carregue o arquivo .pptx aqui (Botão 1).",
        "tut_p4_tit": "Passo 4: A Mágica da IA",
        "tut_p4_txt": "Digite o tema da sua apresentação aqui e clique no botão azul ao lado para a IA gerar tudo do zero. Lembre-se: no plano FREE, isso é bloqueado.",
        "tut_p4b_tit": "Passo 4.1: O Botão Mágico (Mais Fácil)",
        "tut_p4b_txt": "Deu branco e não sabe como pedir para a IA? Clique aqui! O Assistente vai te fazer 3 perguntinhas super fáceis e fará todo o trabalho duro de escrever o comando perfeito para você. É à prova de falhas!",
        "tut_p5_tit": "Passo 5: A Escolha das Imagens",
        "tut_p5_txt": "Após a IA processar o seu tema, uma nova janela vai se abrir automaticamente. Nela, você poderá escolher as fotos sugeridas para cada slide ou marcar 'Não usar imagem'. Só depois disso a apresentação nasce!",
        "tut_p6_tit": "Passo 6: Máquina do Tempo",
        "tut_p6_txt": "O app salva suas gerações recentes no seu PC. Use este botão para recuperar um arquivo que você gerou anteriormente sem gastar seus créditos na nuvem.",
        "tut_p7_tit": "Passo 7: Formatações Prontas",
        "tut_p7_txt": "Use esta caixa para aplicar Formatações Prontas (Presets). O aplicativo ajustará a paleta de cores inteira automaticamente para você ter um ponto de partida.",
        "tut_p8_tit": "Passo 8: Cor dos Títulos",
        "tut_p8_txt": "Clique aqui para escolher a cor que será aplicada exclusivamente aos Títulos dos slides.",
        "tut_p9_tit": "Passo 9: Fonte dos Títulos",
        "tut_p9_txt": "Selecione uma fonte nativa para os Títulos ou use o botão '+' para adicionar uma fonte específica instalada no seu PC.",
        "tut_p10_tit": "Passo 10: Cor do Texto",
        "tut_p10_txt": "Defina a cor para o corpo do texto e para os cartões explicativos. Fica tudo independente dos títulos!",
        "tut_p11_tit": "Passo 11: Fonte do Texto",
        "tut_p11_txt": "Assim como nos títulos, escolha a família de fonte que será usada em todo o conteúdo de texto da apresentação.",
        "tut_p12_tit": "Passo 12: Fundo dos Cards",
        "tut_p12_txt": "A IA pode gerar cartões para separar as informações. Se quiser destacar essas caixas com uma cor de fundo específica, escolha aqui (Botão 3).",
        "tut_p13_tit": "Passo 13: Fundo do Slide",
        "tut_p13_txt": "Use o Botão 4 para carregar uma imagem do seu computador que servirá como textura ou fundo (background) para a apresentação inteira.",
        "tut_p14_tit": "Passo 14: Escala de Imagens",
        "tut_p14_txt": "Marque esta caixa para destrancar a barra deslizante. Com ela, você pode diminuir ou aumentar o tamanho das imagens nos slides.",
        "tut_p15_tit": "Passo 15: Escala de Texto",
        "tut_p15_txt": "Achou a letra pequena? Marque aqui (Item 5.1) e aumente a proporção da fonte de toda a apresentação de uma vez só.",
        "tut_p16_tit": "Passo 16: O Mini-Slide (Preview)",
        "tut_p16_txt": "Olhe para cá! Todas as cores, fontes, fundos e escalas que você alterar serão refletidas aqui em tempo real para você ver como vai ficar.",
        "tut_p17_tit": "Passo 17: Modo Apresentador",
        "tut_p17_txt": "Deixe marcado para a IA gerar um roteiro do que você deve falar e colocá-lo nas anotações do PowerPoint. Aqui você também controla a barra azul.",
        "tut_p18_tit": "Passo 18: O Grande Final",
        "tut_p18_txt": "Tudo pronto e configurado? Clique aqui para processar todas as suas escolhas, aplicar o design e salvar o seu arquivo PPTX final.",
        "tut_p19_tit": "Passo 19: Exportar PDF",
        "tut_p19_txt": "Com a apresentação pronta e salva, você pode usar este botão vermelho para convertê-la imediatamente para PDF com um único clique!\n\nPronto! O palco é seu.",
        
        "auth_title": "Conta VegaTech",
        "auth_tab_login": "Login",
        "auth_tab_cad": "Criar Conta",
        "auth_log_title": "Já tem uma conta? Acesse:",
        "auth_email": "E-mail",
        "auth_senha": "Senha",
        "auth_btn_entrar": "Entrar",
        "auth_cad_title": "Novo por aqui? Cadastre-se:",
        "cad_chk_gringo": "Sou de fora do Brasil (International User)",
        "auth_nome": "Nome Completo",
        "auth_doc_ph": "Apenas números",
        "auth_lbl_pais": "País (Country):",
        "auth_senha_nova": "Crie uma Senha",
        "auth_btn_criar": "Criar Conta",
        "btn_conta": "👤 Minha Conta",
        "btn_avisos": "📢 Avisos",
        "cfg_tab_editor": "Editor",
        "lbl_editor": "Programa para abrir a apresentação após gerar:",
        "editor_detect_none": "⚠️ Nenhum editor detectado no sistema.",
        "editor_detect_found": "Programas detectados no seu computador:",
        "editor_opt_system": "Sistema (Padrão)",
        "editor_opt_none": "Nenhum (Apenas abrir a pasta onde salvou)",
        "msg_pdf_independent_success": "Apresentação convertida para PDF de forma totalmente independente e offline!",
        "msg_pdf_independent_fail": "O app precisa de um motor de renderização visual instalado na máquina para gerar o PDF offline. NENHUM foi encontrado!\n\nInstale o LibreOffice (gratuito) para independência total, ou o PowerPoint.",
        "msg_pdf_fail_generic": "Falha ao converter.\n\nDetalhes:\n{}",
        "msg_sucesso": "Sucesso",
        "msg_erro": "Erro",
        "msg_aviso": "Aviso",
        "msg_erro_pdf": "Erro no PDF",
        
        "msg_sys_editor_fail_tit": "App Padrão não encontrado",
        "msg_sys_editor_fail_msg": "Seu sistema não soube como abrir o arquivo da apresentação automaticamente.\n\nAbrimos a pasta onde o arquivo foi salvo para você. Recomendamos que vá em '⚙️ Configurações / Licença' > 'Editor' e mude a opção para o programa que você tem instalado.",
        
        "btn_assistida": "✨ Criação\nAssistida",
        "ast_title": "Assistente de Criação Passo a Passo",
        "ast_btn_voltar": "⬅️ Voltar",
        "ast_btn_avancar": "Avançar ➡️",
        "ast_btn_gerar": "🚀 Gerar Apresentação",
        "ast_p0_tit": "Bem-vindo ao Assistente!",
        "ast_p0_msg": "Vamos criar sua apresentação juntos em 3 passos simples.\n\nEu vou fazer algumas perguntas fáceis e, com base nas suas respostas, montarei o comando perfeito para a Inteligência Artificial.\n\nClique em 'Avançar' para começar.",
        "ast_p1_tit": "Passo 1: Quantidade de Slides",
        "ast_p1_msg": "Quantos slides você quer que a apresentação tenha no total?",
        "ast_p2_tit": "Passo 2: O Tema",
        "ast_p2_msg": "Sobre o que é a sua apresentação? (Ex: 'Reunião de resultados do trimestre', 'Aula sobre a Revolução Francesa')",
        "ast_p3_tit": "Passo 3: Imagens",
        "ast_p3_msg": "Você quer que a IA sugira imagens para os slides? Se sim, em quantos deles?",
        "ast_p3_opt_todos": "Em todos os slides",
        "ast_p3_opt_nenhum": "Não quero imagens",
        "ast_p4_tit": "Resumo da Obra",
        "ast_p4_resumo": "Tudo pronto!\n\nVocê pediu uma apresentação com <b>{} slides</b> sobre o tema:\n<i>'{}'</i>\n\nImagens solicitadas para: <b>{}</b>.\n\nClique em 'Gerar Apresentação' para a IA assumir o controle!",
    },
    "en": {
        "btn_tutorial": "📚 How to Use",
        "btn_config": "⚙️ Settings / License",
        "btn_novidades": "📋 What's New",
        "btn_avisos": "📢 Notices",
        "btn_buscando": "⏳ Fetching...",
        "nov_janela": "📋 What's New - VegaSlides ({})",
        "nov_header": "<b>What's new in version {}:</b>",
        "nov_btn_ok": "Got it",
        "msg_update_titulo": "🚀 App Updated ({})!",
        "msg_update_texto": "<b>VegaSlides has been updated to version {}!</b><br><br>Click the '📋 What's New' button at the top of the screen to see all the details of the improvements downloaded directly from the server.",
        "msg_update_vazio": "No new features registered for this version on the server.",
        "msg_update_erro_api": "Could not retrieve the release notes from the server at this time.",
        "msg_update_erro_con": "Failed to connect to the Mothership:\n{}",
        "btn_load": "1. Load Ready Presentation (.pptx)",
        "lbl_pptx_vazio": "No file selected",
        "lbl_titulo_ia": "🧠 Artificial Intelligence Creation Engine:",
        "txt_tema_placeholder": "Enter the topic for the AI to create the presentation from scratch...",
        "btn_ia": "Create Presentation\nAutomatically (AI)",
        "btn_historico": "🕒 Recover\nSaved",
        "lbl_presets": "✨ Ready Formats (Presets):",
        "lbl_cor_titulos": "2. Titles Color:",
        "btn_cor_titulos_btn": "🎨 Titles Color",
        "lbl_cor_textos": "2.1. Text Color:",
        "btn_cor_textos_btn": "🎨 Text Color (Body/Cards)",
        "btn_add_font": "➕ New Font",
        "lbl_fonte_titulos": "📝 Titles Font:",
        "lbl_fonte_textos": "📝 Text Font:",
        "btn_fill_color": "3. Choose Cards Background Color (Optional)",
        "btn_bg": "4. Slide Background (Optional)",
        "lbl_bg_preview": "No image",
        "chk_scale": "5. Image Scale:",
        "chk_text_scale": "5.1. Increase text size by:",
        "lbl_preview_text_title": "Example Title",
        "lbl_preview_text_body": "This is the body text.<br>See how it scales.",
        "chk_notes": "5.2. Insert Speaker Script in native notes",
        "chk_barra_lateral": "5.3. Show blue sidebar",
        "btn_save": "6. Process Presentation and Save",
        "btn_pdf": "7. Convert current PPTX to PDF",
        "txt_tema_lock": "🔒 Smart Generation locked (FREE License). Click here to subscribe.",
        
        "cfg_title": "⚙️ App Settings",
        "cfg_tab_lic": "License",
        "cfg_tab_ia": "Artificial Intelligence",
        "cfg_tab_vis": "Appearance",
        "cfg_lbl_lic": "<b>💳 PLAN AND SUBSCRIPTION MANAGEMENT</b><br><br>Select the desired license below to unlock presentation generation. The <b>SAAS ELITE</b> plan unlocks Cloudflare AI, while the <b>Standard SAAS</b> uses Google Gemini.<br><br><i>(Choose the plan and click Save to open the store)</i>",
        "cfg_status_lic": "<b>Current License Status:</b>",
        "cfg_lbl_idioma": "Language / Idioma:",
        "cfg_lbl_tema": "App Theme:",
        "cfg_lbl_zoom": "🔎 Screen Zoom (Accessibility):",
        "cfg_btn_salvar": "Save Settings",
        "cfg_btn_buscar": "🔄 Fetch Models",
        "cfg_btn_load_cf": "🔄 Load CF",
        "cfg_aviso_saas": "✅ <b>SaaS License Active</b>\nThe main engine is unlocked.",
        "cfg_chk_gemini": "🔵 Use Google Gemini (Default)",
        "cfg_lbl_key_gemini": "Gemini API Key (BYOK):",
        "cfg_lbl_modelo": "Model:",
        "cfg_chk_cf": "🟠 Use Cloudflare Workers AI",
        "cfg_btn_upgrade": "⭐ Upgrade ELITE",
        "cfg_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "cfg_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        
        "tema_escuro": "Dark",
        "tema_claro": "Light",
        "lic_free": "FREE (Manual Edit)",
        "lic_byok": "BYOK (Your Key)",
        "lic_saas": "SAAS (Built-in Key)",
        "font_default": "Theme Default",
        "preset_manual": "Custom (Manual)",
        "preset_corp": "Corporate Blue",
        "preset_dark": "Classic Dark Mode",
        "preset_clean": "Clean Minimalist",
        "ia_saas_active": "✅ <b>SaaS License Active</b>\nMain engine is unlocked.",
        "ia_chk_gemini": "🔵 Use Google Gemini (Default)",
        "ia_chk_cf": "🟠 Use Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Gemini API Key (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Model:",
        "btn_upgrade_elite": "⭐ ELITE Upgrade",
        
        "loja_titulo": "🛒 VegaTech Store - VegaSlides",
        "loja_loading": "⏳ Loading available plans...",
        "loja_cupom": "Have a discount coupon? (Optional)",
        "loja_escolha": "Choose the Ideal Package for You:",
        "loja_btn_assinar": "SUBSCRIBE NOW",
        "loja_vazio": "No plans configured in Master.",
        "loja_gerando": "Generating secure payment environment...",
        
        "tut_btn_sair": "❌ Exit Tutorial",
        "tut_btn_prox": "Got it, Next ➔",
        "tut_btn_fim": "Finish Tutorial ✔️",
        "tut_p1_tit": "Step 1: The Engine and License",
        "tut_p1_txt": "Here you configure your API key (BYOK) or activate your SAAS plan. Without this, the Artificial Intelligence won't work!",
        "tut_p1b_tit": "Step 1.1: The Presentation Editor",
        "tut_p1b_txt": "Still in the Settings, under the 'Editor' tab, you can define if the app should automatically open PowerPoint ou another program at the end or just reveal the saved folder for you.",
        "tut_p2_tit": "Step 2: Stay Updated",
        "tut_p2_txt": "Whenever the app updates, click here to see what changed and what new features were added directly from the server.",
        "tut_p3_tit": "Step 3: Manual Editing",
        "tut_p3_txt": "If you already have a ready presentation and just want to use our app to apply a design or convert it to PDF, load the .pptx file here (Button 1).",
        "tut_p4_tit": "Step 4: AI Magic",
        "tut_p4_txt": "Type your presentation topic here and click the blue button next to it for the AI to generate everything from scratch. Remember: on the FREE plan, this is locked.",
        "tut_p4b_tit": "Step 4.1: The Magic Button (Easier)",
        "tut_p4b_txt": "Blanked out and don't know how to ask the AI? Click here! The Wizard will ask you 3 super easy questions and do all the hard work of writing the perfect command for you. It's foolproof!",
        "tut_p5_tit": "Step 5: Choosing Images",
        "tut_p5_txt": "After the AI processes your topic, a new window will open automatically. There, you can choose the suggested photos for each slide or check 'Do not use image'. Only after this is the presentation born!",
        "tut_p6_tit": "Step 6: Time Machine",
        "tut_p6_txt": "The app saves your recent generations on your PC. Use this button to recover a file you generated previously without spending your cloud credits.",
        "tut_p7_tit": "Step 7: Ready Formats",
        "tut_p7_txt": "Use this box to apply Ready Formats (Presets). The app will automatically adjust the entire color palette to give you a starting point.",
        "tut_p8_tit": "Step 8: Title Color",
        "tut_p8_txt": "Click here to choose the color that will be applied exclusively to the slide Titles.",
        "tut_p9_tit": "Step 9: Title Font",
        "tut_p9_txt": "Select a native font for the Titles or use the '+' button to add a specific font installed on your PC.",
        "tut_p10_tit": "Step 10: Text Color",
        "tut_p10_txt": "Set the color for the body text and explanatory cards. Everything is independent of the titles!",
        "tut_p11_tit": "Step 11: Text Font",
        "tut_p11_txt": "Just like with titles, choose the font family that will be used for all text content in the presentation.",
        "tut_p12_tit": "Step 12: Cards Background",
        "tut_p12_txt": "The AI can generate cards to separate information. If you want to highlight these boxes with a specific background color, choose here (Button 3).",
        "tut_p13_tit": "Step 13: Slide Background",
        "tut_p13_txt": "Use Button 4 to load an image from your computer that will serve as the texture or background for the entire presentation.",
        "tut_p14_tit": "Step 14: Image Scale",
        "tut_p14_txt": "Check this box to unlock the slider. With it, you can decrease or increase the size of the images on the slides.",
        "tut_p15_tit": "Step 15: Text Scale",
        "tut_p15_txt": "Think the font is small? Check here (Item 5.1) and increase the font proportion of the entire presentation at once.",
        "tut_p16_tit": "Step 16: The Mini-Slide (Preview)",
        "tut_p16_txt": "Look here! All colors, fonts, backgrounds, and scales you alter will be reflected here in real time so you can see how it looks.",
        "tut_p17_tit": "Step 17: Presenter Mode",
        "tut_p17_txt": "Leave checked for the AI to generate a script of what you should say and place it in PowerPoint's notes. You also control the blue sidebar here.",
        "tut_p18_tit": "Step 18: The Grand Finale",
        "tut_p18_txt": "All set and configured? Click here to process all your choices, apply the design, and save your final PPTX file.",
        "tut_p19_tit": "Step 19: Export to PDF",
        "tut_p19_txt": "With the presentation ready and saved, you can use this red button to instantly convert it to PDF with a single click!\n\nDone! The stage is yours.",
        
        "auth_title": "VegaTech Account",
        "auth_tab_login": "Login",
        "auth_tab_cad": "Create Account",
        "auth_log_title": "Already have an account? Sign in:",
        "auth_email": "E-mail",
        "auth_senha": "Password",
        "auth_btn_entrar": "Sign In",
        "auth_cad_title": "New here? Register:",
        "cad_chk_gringo": "I am an international user",
        "auth_nome": "Full Name",
        "auth_doc_ph": "Numbers only",
        "auth_lbl_pais": "Country:",
        "auth_senha_nova": "Create a Password",
        "auth_btn_criar": "Create Account",
        "btn_conta": "👤 My Account",
        
        "cfg_tab_editor": "Editor",
        "lbl_editor": "Program to open the presentation after generating:",
        "editor_detect_none": "⚠️ No editor detected on the system.",
        "editor_detect_found": "Programs detected on your computer:",
        "editor_opt_system": "System (Default)",
        "editor_opt_none": "None (Just open the saved folder)",
        "msg_pdf_independent_success": "Presentation converted to PDF completely independently and offline!",
        "msg_pdf_independent_fail": "The app needs a visual rendering engine installed on the machine to generate the PDF offline. NONE were found!\n\nInstall LibreOffice (free) for total independence, or PowerPoint.",
        "msg_pdf_fail_generic": "Failed to convert.\n\nDetails:\n{}",
        "msg_sucesso": "Success",
        "msg_erro": "Error",
        "msg_aviso": "Warning",
        "msg_erro_pdf": "PDF Error",
        
        "msg_sys_editor_fail_tit": "Default App Not Found",
        "msg_sys_editor_fail_msg": "Your system didn't know how to open the presentation file automatically.\n\nWe opened the folder where the file was saved for you. We recommend going to '⚙️ Settings / License' > 'Editor' and changing the option to a program you have installed.",
        
        "btn_assistida": "✨ Assisted\nCreation",
        "ast_title": "Step-by-Step Creation Wizard",
        "ast_btn_voltar": "⬅️ Back",
        "ast_btn_avancar": "Next ➡️",
        "ast_btn_gerar": "🚀 Generate Presentation",
        "ast_p0_tit": "Welcome to the Wizard!",
        "ast_p0_msg": "Let's create your presentation together in 3 simple steps.\n\nI will ask you a few easy questions, and based on your answers, I will build the perfect command for the AI.\n\nClick 'Next' to start.",
        "ast_p1_tit": "Step 1: Number of Slides",
        "ast_p1_msg": "How many slides do you want the presentation to have in total?",
        "ast_p2_tit": "Step 2: The Topic",
        "ast_p2_msg": "What is your presentation about? (E.g., 'Quarterly results meeting', 'Lesson on the French Revolution')",
        "ast_p3_tit": "Step 3: Images",
        "ast_p3_msg": "Do you want the AI to suggest images for the slides? If so, in how many of them?",
        "ast_p3_opt_todos": "In all slides",
        "ast_p3_opt_nenhum": "No images",
        "ast_p4_tit": "Summary",
        "ast_p4_resumo": "All set!\n\nYou asked for a presentation with <b>{} slides</b> on the topic:\n<i>'{}'</i>\n\nImages requested for: <b>{}</b>.\n\nClick 'Generate Presentation' for the AI to take over!",
    }
}