# idiomas.py

_idioma_atual = "pt"

def set_idioma(sigla):
    global _idioma_atual
    _idioma_atual = sigla

def tr(chave):
    """Retorna o texto no idioma atual. Se não achar, retorna a própria chave."""
    return _DICIONARIO.get(_idioma_atual, {}).get(chave, chave)

_DICIONARIO = {
    "pt": {
        "btn_tutorial": "📚 Como Usar",
        "btn_config": "⚙️ Configurações / Licença",
        "btn_novidades": "📋 Novidades",
        "btn_buscando": "⏳ Buscando...",
        "nov_janela": "📋 Novidades - SmartSlides Pro ({})",
        "nov_header": "<b>O que há de novo na versão {}:</b>",
        "nov_btn_ok": "Entendi",
        "msg_update_titulo": "🚀 Aplicativo Atualizado ({})!",
        "msg_update_texto": "<b>O SmartSlides Pro foi atualizado para a versão {}!</b><br><br>Clique no botão '📋 Novidades' no topo da tela para ver todos os detalhes das melhorias baixadas diretamente do servidor.",
        "msg_update_vazio": "Sem novidades registradas para esta versão no servidor.",
        "msg_update_erro_api": "Não foi possível resgatar as novidades do servidor no momento.",
        "msg_update_erro_con": "Falha de conexão com a Nave-Mãe:\n{}",
        "btn_load": "1. Carregar Apresentação Pronta (.pptx)",
        "lbl_pptx_vazio": "Nenhum arquivo selecionado",
        "lbl_titulo_ia": "🧠 Motor de Criação por Inteligência Artificial:",
        "txt_tema_placeholder": "Digite o tema para a IA criar a apresentação do zero...",
        "btn_ia": "Criar Apresentação\nAutomática (IA)",
        "btn_historico": "🕒 Recuperar\nSalvo",
        "lbl_presets": "✨ Formatações Prontas (Presets):",
        "lbl_cor_titulos": "2. Cor dos Títulos:",
        "btn_cor_titulos_btn": "🎨 Cor dos Títulos",
        "lbl_cor_textos": "2.1. Cor dos Textos:",
        "btn_cor_textos_btn": "🎨 Cor dos Textos (Corpo/Cards)",
        "btn_add_font": "➕ Nova Fonte",
        "lbl_fonte_titulos": "📝 Fonte dos Títulos:",
        "lbl_fonte_textos": "📝 Fonte dos Textos:",
        "btn_fill_color": "3. Escolher Cor de Fundo dos Cards (Opcional)",
        "btn_bg": "4. Fundo do Slide (Opcional)",
        "lbl_bg_preview": "Sem imagem",
        "chk_scale": "5. Escala das imagens:",
        "chk_text_scale": "5.1. Aumentar textos em:",
        "lbl_preview_text_title": "Título Exemplo",
        "lbl_preview_text_body": "Este é o corpo do texto.<br>Veja como ele cresce e muda.",
        "chk_notes": "5.2. Inserir Roteiro do Apresentador nas anotações nativas",
        "chk_barra_lateral": "5.3. Exibir barra azul lateral",
        "btn_save": "6. Processar Apresentação e Salvar",
        "btn_pdf": "7. Converter o PPTX atual para PDF",
        "txt_tema_lock": "🔒 Geração Inteligente bloqueada (Licença FREE). Clique aqui para assinar.",
        
        "cfg_title": "⚙️ Configurações do App",
        "cfg_tab_lic": "Licença",
        "cfg_tab_ia": "Inteligência Artificial",
        "cfg_tab_vis": "Aparência",
        "cfg_lbl_lic": "<b>💳 GESTÃO DE PLANOS E ASSINATURAS</b><br><br>Selecione a licença desejada abaixo para liberar a geração de apresentações. O plano <b>SAAS ELITE</b> desbloqueia a Inteligência Artificial da Cloudflare, enquanto o <b>SAAS Padrão</b> usa o Google Gemini.<br><br><i>(Escolha o plano e clique em Salvar para abrir a loja)</i>",
        "cfg_status_lic": "<b>Status da Licença atual:</b>",
        "cfg_lbl_idioma": "Idioma / Language:",
        "cfg_lbl_tema": "Tema do Aplicativo:",
        "cfg_lbl_zoom": "🔎 Zoom da Tela (Acessibilidade):",
        "cfg_btn_salvar": "Salvar Configurações",
        "cfg_btn_buscar": "🔄 Buscar Modelos",
        "cfg_btn_load_cf": "🔄 Carregar CF",
        
        "tema_escuro": "Escuro",
        "tema_claro": "Claro",
        "lic_free": "FREE (Edição Manual)",
        "lic_byok": "BYOK (Sua Chave)",
        "lic_saas": "SAAS (Chave Embutida)",
        "font_default": "Padrão do Tema",
        "preset_manual": "Personalizado (Manual)",
        "preset_corp": "Corporativo Azul",
        "preset_dark": "Dark Mode Clássico",
        "preset_clean": "Minimalista Clean",
        "ia_saas_active": "✅ <b>Licença SaaS Ativa</b>\nO motor principal está liberado.",
        "ia_chk_gemini": "🔵 Usar Google Gemini (Padrão)",
        "ia_chk_cf": "🟠 Usar Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Chave de API Gemini (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Modelo:",
        "btn_upgrade_elite": "⭐ Upgrade ELITE",
        
        "loja_titulo": "🛒 Loja VegaTech - SmartSlides Pro",
        "loja_loading": "⏳ A carregar planos disponíveis...",
        "loja_cupom": "Tem um cupom de desconto? (Opcional)",
        "loja_escolha": "Escolha o Pacote Ideal para Você:",
        "loja_btn_assinar": "ASSINAR AGORA",
        "loja_vazio": "Nenhum plano configurado no Master.",
        "loja_gerando": "A gerar ambiente seguro de pagamento...",
        
        "tut_btn_sair": "❌ Sair do Tutorial",
        "tut_btn_prox": "Entendi, Próximo ➔",
        "tut_btn_fim": "Concluir Tutorial ✔️",
        "tut_olhe_esq": "⬅️ OLHE PARA A ESQUERDA\n\n",
        "tut_olhe_cima": "⬆️ OLHE PARA A CAIXA ACIMA\n\n",
        "tut_olhe_baixo": "⬇️ OLHE PARA OS BOTÕES ABAIXO\n\n",
        "tut_p1_tit": "Passo 1: O Início e as Licenças",
        "tut_p1_txt": "Bem-vindo ao SmartSlides Pro!\n\nVocê tem dois caminhos:\n1. Digite um tema na caixa acima e deixe a IA criar a apresentação do zero.\n\n⚠️ ATENÇÃO: A Inteligência Artificial é um recurso PREMIUM. No plano FREE (Grátis), a IA não funciona e o botão fica bloqueado! Você precisa ativar o plano SAAS ou colocar sua chave BYOK no botão '⚙️ Configurações / Licença' lá no topo.\n\n2. Se você já tem um PPTX pronto e só quer maquiá-lo, use o 'Botão 1' lá em cima.",
        "tut_p2_tit": "Passo 2: As Imagens",
        "tut_p2_txt": "Após a IA pensar, uma nova janela vai se abrir.\n\nNela, você escolherá as fotos sugeridas para cada slide. Se não quiser foto em algum slide, marque a opção 'Não usar imagem'. Só depois de confirmar as fotos é que a apresentação nasce!",
        "tut_p3_tit": "Passo 3: A Maquiagem",
        "tut_p3_txt": "Aqui começa o design da sua apresentação.\n\n- Use esta caixa ao lado para aplicar Formatações Prontas (Presets).\n- Ou, logo abaixo, mude manualmente a Cor do Texto, a Cor de Fundo e as Fontes dos Títulos e do Corpo.",
        "tut_p4_tit": "Passo 4: Os Ajustes Finos",
        "tut_p4_txt": "Veja as caixinhas e sliders abaixo!\n\nUse-os para diminuir o tamanho das fotos ou aumentar o tamanho das letras. \n\nLembre-se: Você precisa marcar a caixinha (Checkbox) para destrancar o slider. Olhe para o Mini-Slide no rodapé, ele mostra a mágica acontecendo em tempo real!",
        "tut_p5_tit": "Passo 5: O Grande Final",
        "tut_p5_txt": "Tudo pronto?\n\nClique no botão cinza escuro abaixo ('Processar Apresentação e Salvar'). O aplicativo vai aplicar todas as cores, fontes e recortes que você escolheu e gerar o seu arquivo PPTX final na hora.\n\nPronto! Já pode ir pro palco."
    },
    "en": {
        "btn_tutorial": "📚 How to Use",
        "btn_config": "⚙️ Settings / License",
        "btn_novidades": "📋 What's New",
        "btn_buscando": "⏳ Fetching...",
        "nov_janela": "📋 What's New - SmartSlides Pro ({})",
        "nov_header": "<b>What's new in version {}:</b>",
        "nov_btn_ok": "Got it",
        "msg_update_titulo": "🚀 App Updated ({})!",
        "msg_update_texto": "<b>SmartSlides Pro has been updated to version {}!</b><br><br>Click the '📋 What's New' button at the top of the screen to see all the details of the improvements downloaded directly from the server.",
        "msg_update_vazio": "No new features registered for this version on the server.",
        "msg_update_erro_api": "Could not retrieve the release notes from the server at this time.",
        "msg_update_erro_con": "Failed to connect to the Mothership:\n{}",
        "btn_load": "1. Load Ready Presentation (.pptx)",
        "lbl_pptx_vazio": "No file selected",
        "lbl_titulo_ia": "🧠 Artificial Intelligence Creation Engine:",
        "txt_tema_placeholder": "Enter the topic for the AI to create the presentation from scratch...",
        "btn_ia": "Create Presentation\nAutomatically (AI)",
        "btn_historico": "🕒 Recover\nSaved",
        "lbl_presets": "✨ Ready Formats (Presets):",
        "lbl_cor_titulos": "2. Titles Color:",
        "btn_cor_titulos_btn": "🎨 Titles Color",
        "lbl_cor_textos": "2.1. Text Color:",
        "btn_cor_textos_btn": "🎨 Text Color (Body/Cards)",
        "btn_add_font": "➕ New Font",
        "lbl_fonte_titulos": "📝 Titles Font:",
        "lbl_fonte_textos": "📝 Text Font:",
        "btn_fill_color": "3. Choose Cards Background Color (Optional)",
        "btn_bg": "4. Slide Background (Optional)",
        "lbl_bg_preview": "No image",
        "chk_scale": "5. Image Scale:",
        "chk_text_scale": "5.1. Increase text size by:",
        "lbl_preview_text_title": "Example Title",
        "lbl_preview_text_body": "This is the body text.<br>See how it scales.",
        "chk_notes": "5.2. Insert Speaker Script in native notes",
        "chk_barra_lateral": "5.3. Show blue sidebar",
        "btn_save": "6. Process Presentation and Save",
        "btn_pdf": "7. Convert current PPTX to PDF",
        "txt_tema_lock": "🔒 Smart Generation locked (FREE License). Click here to subscribe.",
        
        "cfg_title": "⚙️ App Settings",
        "cfg_tab_lic": "License",
        "cfg_tab_ia": "Artificial Intelligence",
        "cfg_tab_vis": "Appearance",
        "cfg_lbl_lic": "<b>💳 PLAN AND SUBSCRIPTION MANAGEMENT</b><br><br>Select the desired license below to unlock presentation generation. The <b>SAAS ELITE</b> plan unlocks Cloudflare AI, while the <b>Standard SAAS</b> uses Google Gemini.<br><br><i>(Choose the plan and click Save to open the store)</i>",
        "cfg_status_lic": "<b>Current License Status:</b>",
        "cfg_lbl_idioma": "Language / Idioma:",
        "cfg_lbl_tema": "App Theme:",
        "cfg_lbl_zoom": "🔎 Screen Zoom (Accessibility):",
        "cfg_btn_salvar": "Save Settings",
        "cfg_btn_buscar": "🔄 Fetch Models",
        "cfg_btn_load_cf": "🔄 Load CF",
        
        "tema_escuro": "Dark",
        "tema_claro": "Light",
        "lic_free": "FREE (Manual Edit)",
        "lic_byok": "BYOK (Your Key)",
        "lic_saas": "SAAS (Built-in Key)",
        "font_default": "Theme Default",
        "preset_manual": "Custom (Manual)",
        "preset_corp": "Corporate Blue",
        "preset_dark": "Classic Dark Mode",
        "preset_clean": "Clean Minimalist",
        "ia_saas_active": "✅ <b>SaaS License Active</b>\nMain engine is unlocked.",
        "ia_chk_gemini": "🔵 Use Google Gemini (Default)",
        "ia_chk_cf": "🟠 Use Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Gemini API Key (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Model:",
        "btn_upgrade_elite": "⭐ ELITE Upgrade",
        
        "loja_titulo": "🛒 VegaTech Store - SmartSlides Pro",
        "loja_loading": "⏳ Loading available plans...",
        "loja_cupom": "Have a discount coupon? (Optional)",
        "loja_escolha": "Choose the Ideal Package for You:",
        "loja_btn_assinar": "SUBSCRIBE NOW",
        "loja_vazio": "No plans configured in Master.",
        "loja_gerando": "Generating secure payment environment...",
        
        "tut_btn_sair": "❌ Exit Tutorial",
        "tut_btn_prox": "Got it, Next ➔",
        "tut_btn_fim": "Finish Tutorial ✔️",
        "tut_olhe_esq": "⬅️ LOOK TO THE LEFT\n\n",
        "tut_olhe_cima": "⬆️ LOOK AT THE BOX ABOVE\n\n",
        "tut_olhe_baixo": "⬇️ LOOK AT THE BUTTONS BELOW\n\n",
        "tut_p1_tit": "Step 1: Getting Started and Licenses",
        "tut_p1_txt": "Welcome to SmartSlides Pro!\n\nYou have two paths:\n1. Type a topic in the box above and let the AI create the presentation from scratch.\n\n⚠️ ATTENTION: Artificial Intelligence is a PREMIUM feature. On the FREE plan, the AI doesn't work and the button is locked! You need to activate the SAAS plan or enter your BYOK key in the '⚙️ Settings / License' button at the top.\n\n2. If you already have a ready PPTX and just want to style it, use 'Button 1' at the top.",
        "tut_p2_tit": "Step 2: The Images",
        "tut_p2_txt": "After the AI thinks, a new window will open.\n\nThere, you will choose the suggested photos for each slide. If you don't want a photo on a slide, check 'Do not use image'. Only after confirming the photos is the presentation born!",
        "tut_p3_tit": "Step 3: The Styling",
        "tut_p3_txt": "Here begins the design of your presentation.\n\n- Use this box to apply Ready Formats (Presets).\n- Or, right below, manually change the Text Color, Background Color, and Fonts for Titles and Body.",
        "tut_p4_tit": "Step 4: Fine Adjustments",
        "tut_p4_txt": "See the checkboxes and sliders below!\n\nUse them to decrease the size of photos or increase the text size. \n\nRemember: You need to check the box (Checkbox) to unlock the slider. Look at the Mini-Slide in the footer, it shows the magic happening in real time!",
        "tut_p5_tit": "Step 5: The Grand Finale",
        "tut_p5_txt": "All set?\n\nClick the dark gray button below ('Process Presentation and Save'). The app will apply all the colors, fonts, and crops you chose and generate your final PPTX file instantly.\n\nDone! You can go to the stage."
    }
}