# idiomas.py

_idioma_atual = "pt"

def set_idioma(sigla):
    global _idioma_atual
    _idioma_atual = sigla

def tr(chave):
    """Retorna o texto no idioma atual. Se não achar, retorna a própria chave."""
    return _DICIONARIO.get(_idioma_atual, {}).get(chave, chave)

_DICIONARIO = {
    "pt": {
        "btn_tutorial": "📚 Como Usar",
        "btn_config": "⚙️ Configurações / Licença",
        "btn_novidades": "📋 Novidades",
        "btn_buscando": "⏳ Buscando...",
        "nov_janela": "📋 Novidades - SmartSlides Pro ({})",
        "nov_header": "<b>O que há de novo na versão {}:</b>",
        "nov_btn_ok": "Entendi",
        "msg_update_titulo": "🚀 Aplicativo Atualizado ({})!",
        "msg_update_texto": "<b>O SmartSlides Pro foi atualizado para a versão {}!</b><br><br>Clique no botão '📋 Novidades' no topo da tela para ver todos os detalhes das melhorias baixadas diretamente do servidor.",
        "msg_update_vazio": "Sem novidades registradas para esta versão no servidor.",
        "msg_update_erro_api": "Não foi possível resgatar as novidades do servidor no momento.",
        "msg_update_erro_con": "Falha de conexão com a Nave-Mãe:\n{}",
        "btn_load": "1. Carregar Apresentação Pronta (.pptx)",
        "lbl_pptx_vazio": "Nenhum arquivo selecionado",
        "lbl_titulo_ia": "🧠 Motor de Criação por Inteligência Artificial:",
        "txt_tema_placeholder": "Digite o tema para a IA criar a apresentação do zero...",
        "btn_ia": "Criar Apresentação\nAutomática (IA)",
        "btn_historico": "🕒 Recuperar\nSalvo",
        "lbl_presets": "✨ Formatações Prontas (Presets):",
        "lbl_cor_titulos": "2. Cor dos Títulos:",
        "btn_cor_titulos_btn": "🎨 Cor dos Títulos",
        "lbl_cor_textos": "2.1. Cor dos Textos:",
        "btn_cor_textos_btn": "🎨 Cor dos Textos (Corpo/Cards)",
        "btn_add_font": "➕ Nova Fonte",
        "lbl_fonte_titulos": "📝 Fonte dos Títulos:",
        "lbl_fonte_textos": "📝 Fonte dos Textos:",
        "btn_fill_color": "3. Escolher Cor de Fundo dos Cards (Opcional)",
        "btn_bg": "4. Fundo do Slide (Opcional)",
        "lbl_bg_preview": "Sem imagem",
        "chk_scale": "5. Escala das imagens:",
        "chk_text_scale": "5.1. Aumentar textos em:",
        "lbl_preview_text_title": "Título Exemplo",
        "lbl_preview_text_body": "Este é o corpo do texto.<br>Veja como ele cresce e muda.",
        "chk_notes": "5.2. Inserir Roteiro do Apresentador nas anotações nativas",
        "chk_barra_lateral": "5.3. Exibir barra azul lateral",
        "btn_save": "6. Processar Apresentação e Salvar",
        "btn_pdf": "7. Converter o PPTX atual para PDF",
        "txt_tema_lock": "🔒 Geração Inteligente bloqueada (Licença FREE). Clique aqui para assinar.",
        
        "cfg_title": "⚙️ Configurações do App",
        "cfg_tab_lic": "Licença",
        "cfg_tab_ia": "Inteligência Artificial",
        "cfg_tab_vis": "Aparência",
        "cfg_lbl_lic": "<b>💳 GESTÃO DE PLANOS E ASSINATURAS</b><br><br>Selecione a licença desejada abaixo para liberar a geração de apresentações. O plano <b>SAAS ELITE</b> desbloqueia a Inteligência Artificial da Cloudflare, enquanto o <b>SAAS Padrão</b> usa o Google Gemini.<br><br><i>(Escolha o plano e clique em Salvar para abrir a loja)</i>",
        "cfg_status_lic": "<b>Status da Licença atual:</b>",
        "cfg_lbl_idioma": "Idioma / Language:",
        "cfg_lbl_tema": "Tema do Aplicativo:",
        "cfg_lbl_zoom": "🔎 Zoom da Tela (Acessibilidade):",
        "cfg_btn_salvar": "Salvar Configurações",
        "cfg_btn_buscar": "🔄 Buscar Modelos",
        "cfg_btn_load_cf": "🔄 Carregar CF",
        
        "tema_escuro": "Escuro",
        "tema_claro": "Claro",
        "lic_free": "FREE (Edição Manual)",
        "lic_byok": "BYOK (Sua Chave)",
        "lic_saas": "SAAS (Chave Embutida)",
        "font_default": "Padrão do Tema",
        "preset_manual": "Personalizado (Manual)",
        "preset_corp": "Corporativo Azul",
        "preset_dark": "Dark Mode Clássico",
        "preset_clean": "Minimalista Clean",
        "ia_saas_active": "✅ <b>Licença SaaS Ativa</b>\nO motor principal está liberado.",
        "ia_chk_gemini": "🔵 Usar Google Gemini (Padrão)",
        "ia_chk_cf": "🟠 Usar Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Chave de API Gemini (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Modelo:",
        "btn_upgrade_elite": "⭐ Upgrade ELITE",
        
        "loja_titulo": "🛒 Loja VegaTech - SmartSlides Pro",
        "loja_loading": "⏳ A carregar planos disponíveis...",
        "loja_cupom": "Tem um cupom de desconto? (Opcional)",
        "loja_escolha": "Escolha o Pacote Ideal para Você:",
        "loja_btn_assinar": "ASSINAR AGORA",
        "loja_vazio": "Nenhum plano configurado no Master.",
        "loja_gerando": "A gerar ambiente seguro de pagamento...",
        
        "tut_btn_sair": "❌ Sair do Tutorial",
        "tut_btn_prox": "Entendi, Próximo ➔",
        "tut_btn_fim": "Concluir Tutorial ✔️",
        "tut_p1_tit": "Passo 1: O Motor e a Licença",
        "tut_p1_txt": "Aqui você configura sua chave de API (BYOK) ou ativa seu plano SAAS. Sem isso, a Inteligência Artificial não funciona!",
        "tut_p2_tit": "Passo 2: Fique Atualizado",
        "tut_p2_txt": "Sempre que o app atualizar, clique aqui para ver o que mudou e quais novos recursos foram adicionados diretamente pelo servidor.",
        "tut_p3_tit": "Passo 3: Edição Manual",
        "tut_p3_txt": "Se você já tem uma apresentação pronta e quer apenas usar o nosso aplicativo para aplicar um design ou converter em PDF, carregue o arquivo .pptx aqui (Botão 1).",
        "tut_p4_tit": "Passo 4: A Mágica da IA",
        "tut_p4_txt": "Digite o tema da sua apresentação aqui e clique no botão azul ao lado para a IA gerar tudo do zero. Lembre-se: no plano FREE, isso é bloqueado.",
        "tut_p5_tit": "Passo 5: A Escolha das Imagens",
        "tut_p5_txt": "Após a IA processar o seu tema, uma nova janela vai se abrir automaticamente. Nela, você poderá escolher as fotos sugeridas para cada slide ou marcar 'Não usar imagem'. Só depois disso a apresentação nasce!",
        "tut_p6_tit": "Passo 6: Máquina do Tempo",
        "tut_p6_txt": "O app salva suas gerações recentes no seu PC. Use este botão para recuperar um arquivo que você gerou anteriormente sem gastar seus créditos na nuvem.",
        "tut_p7_tit": "Passo 7: Formatações Prontas",
        "tut_p7_txt": "Use esta caixa para aplicar Formatações Prontas (Presets). O aplicativo ajustará a paleta de cores inteira automaticamente para você ter um ponto de partida.",
        "tut_p8_tit": "Passo 8: Cor dos Títulos",
        "tut_p8_txt": "Clique aqui para escolher a cor que será aplicada exclusivamente aos Títulos dos slides.",
        "tut_p9_tit": "Passo 9: Fonte dos Títulos",
        "tut_p9_txt": "Selecione uma fonte nativa para os Títulos ou use o botão '+' para adicionar uma fonte específica instalada no seu PC.",
        "tut_p10_tit": "Passo 10: Cor do Texto",
        "tut_p10_txt": "Defina a cor para o corpo do texto e para os cartões explicativos. Fica tudo independente dos títulos!",
        "tut_p11_tit": "Passo 11: Fonte do Texto",
        "tut_p11_txt": "Assim como nos títulos, escolha a família de fonte que será usada em todo o conteúdo de texto da apresentação.",
        "tut_p12_tit": "Passo 12: Fundo dos Cards",
        "tut_p12_txt": "A IA pode gerar cartões para separar as informações. Se quiser destacar essas caixas com uma cor de fundo específica, escolha aqui (Botão 3).",
        "tut_p13_tit": "Passo 13: Fundo do Slide",
        "tut_p13_txt": "Use o Botão 4 para carregar uma imagem do seu computador que servirá como textura ou fundo (background) para a apresentação inteira.",
        "tut_p14_tit": "Passo 14: Escala de Imagens",
        "tut_p14_txt": "Marque esta caixa para destrancar a barra deslizante. Com ela, você pode diminuir ou aumentar o tamanho das imagens nos slides.",
        "tut_p15_tit": "Passo 15: Escala de Texto",
        "tut_p15_txt": "Achou a letra pequena? Marque aqui (Item 5.1) e aumente a proporção da fonte de toda a apresentação de uma vez só.",
        "tut_p16_tit": "Passo 16: O Mini-Slide (Preview)",
        "tut_p16_txt": "Olhe para cá! Todas as cores, fontes, fundos e escalas que você alterar serão refletidas aqui em tempo real para você ver como vai ficar.",
        "tut_p17_tit": "Passo 17: Modo Apresentador",
        "tut_p17_txt": "Deixe marcado para a IA gerar um roteiro do que você deve falar e colocá-lo nas anotações do PowerPoint. Aqui você também controla a barra azul.",
        "tut_p18_tit": "Passo 18: O Grande Final",
        "tut_p18_txt": "Tudo pronto e configurado? Clique aqui para processar todas as suas escolhas, aplicar o design e salvar o seu arquivo PPTX final.",
        "tut_p19_tit": "Passo 19: Exportar PDF",
        "tut_p19_txt": "Com a apresentação pronta e salva, você pode usar este botão vermelho para convertê-la imediatamente para PDF com um único clique!\n\nPronto! O palco é seu."
    },
    "en": {
        "btn_tutorial": "📚 How to Use",
        "btn_config": "⚙️ Settings / License",
        "btn_novidades": "📋 What's New",
        "btn_buscando": "⏳ Fetching...",
        "nov_janela": "📋 What's New - SmartSlides Pro ({})",
        "nov_header": "<b>What's new in version {}:</b>",
        "nov_btn_ok": "Got it",
        "msg_update_titulo": "🚀 App Updated ({})!",
        "msg_update_texto": "<b>SmartSlides Pro has been updated to version {}!</b><br><br>Click the '📋 What's New' button at the top of the screen to see all the details of the improvements downloaded directly from the server.",
        "msg_update_vazio": "No new features registered for this version on the server.",
        "msg_update_erro_api": "Could not retrieve the release notes from the server at this time.",
        "msg_update_erro_con": "Failed to connect to the Mothership:\n{}",
        "btn_load": "1. Load Ready Presentation (.pptx)",
        "lbl_pptx_vazio": "No file selected",
        "lbl_titulo_ia": "🧠 Artificial Intelligence Creation Engine:",
        "txt_tema_placeholder": "Enter the topic for the AI to create the presentation from scratch...",
        "btn_ia": "Create Presentation\nAutomatically (AI)",
        "btn_historico": "🕒 Recover\nSaved",
        "lbl_presets": "✨ Ready Formats (Presets):",
        "lbl_cor_titulos": "2. Titles Color:",
        "btn_cor_titulos_btn": "🎨 Titles Color",
        "lbl_cor_textos": "2.1. Text Color:",
        "btn_cor_textos_btn": "🎨 Text Color (Body/Cards)",
        "btn_add_font": "➕ New Font",
        "lbl_fonte_titulos": "📝 Titles Font:",
        "lbl_fonte_textos": "📝 Text Font:",
        "btn_fill_color": "3. Choose Cards Background Color (Optional)",
        "btn_bg": "4. Slide Background (Optional)",
        "lbl_bg_preview": "No image",
        "chk_scale": "5. Image Scale:",
        "chk_text_scale": "5.1. Increase text size by:",
        "lbl_preview_text_title": "Example Title",
        "lbl_preview_text_body": "This is the body text.<br>See how it scales.",
        "chk_notes": "5.2. Insert Speaker Script in native notes",
        "chk_barra_lateral": "5.3. Show blue sidebar",
        "btn_save": "6. Process Presentation and Save",
        "btn_pdf": "7. Convert current PPTX to PDF",
        "txt_tema_lock": "🔒 Smart Generation locked (FREE License). Click here to subscribe.",
        
        "cfg_title": "⚙️ App Settings",
        "cfg_tab_lic": "License",
        "cfg_tab_ia": "Artificial Intelligence",
        "cfg_tab_vis": "Appearance",
        "cfg_lbl_lic": "<b>💳 PLAN AND SUBSCRIPTION MANAGEMENT</b><br><br>Select the desired license below to unlock presentation generation. The <b>SAAS ELITE</b> plan unlocks Cloudflare AI, while the <b>Standard SAAS</b> uses Google Gemini.<br><br><i>(Choose the plan and click Save to open the store)</i>",
        "cfg_status_lic": "<b>Current License Status:</b>",
        "cfg_lbl_idioma": "Language / Idioma:",
        "cfg_lbl_tema": "App Theme:",
        "cfg_lbl_zoom": "🔎 Screen Zoom (Accessibility):",
        "cfg_btn_salvar": "Save Settings",
        "cfg_btn_buscar": "🔄 Fetch Models",
        "cfg_btn_load_cf": "🔄 Load CF",
        
        "tema_escuro": "Dark",
        "tema_claro": "Light",
        "lic_free": "FREE (Manual Edit)",
        "lic_byok": "BYOK (Your Key)",
        "lic_saas": "SAAS (Built-in Key)",
        "font_default": "Theme Default",
        "preset_manual": "Custom (Manual)",
        "preset_corp": "Corporate Blue",
        "preset_dark": "Classic Dark Mode",
        "preset_clean": "Clean Minimalist",
        "ia_saas_active": "✅ <b>SaaS License Active</b>\nMain engine is unlocked.",
        "ia_chk_gemini": "🔵 Use Google Gemini (Default)",
        "ia_chk_cf": "🟠 Use Cloudflare Workers AI",
        "ia_lbl_key_gemini": "Gemini API Key (BYOK):",
        "ia_lbl_acc_cf": "Cloudflare Account ID (BYOK):",
        "ia_lbl_tok_cf": "Cloudflare API Token (BYOK):",
        "ia_lbl_modelo": "Model:",
        "btn_upgrade_elite": "⭐ ELITE Upgrade",
        
        "loja_titulo": "🛒 VegaTech Store - SmartSlides Pro",
        "loja_loading": "⏳ Loading available plans...",
        "loja_cupom": "Have a discount coupon? (Optional)",
        "loja_escolha": "Choose the Ideal Package for You:",
        "loja_btn_assinar": "SUBSCRIBE NOW",
        "loja_vazio": "No plans configured in Master.",
        "loja_gerando": "Generating secure payment environment...",
        
        "tut_btn_sair": "❌ Exit Tutorial",
        "tut_btn_prox": "Got it, Next ➔",
        "tut_btn_fim": "Finish Tutorial ✔️",
        "tut_p1_tit": "Step 1: The Engine and License",
        "tut_p1_txt": "Here you configure your API key (BYOK) or activate your SAAS plan. Without this, the Artificial Intelligence won't work!",
        "tut_p2_tit": "Step 2: Stay Updated",
        "tut_p2_txt": "Whenever the app updates, click here to see what changed and what new features were added directly from the server.",
        "tut_p3_tit": "Step 3: Manual Editing",
        "tut_p3_txt": "If you already have a ready presentation and just want to use our app to apply a design or convert it to PDF, load the .pptx file here (Button 1).",
        "tut_p4_tit": "Step 4: AI Magic",
        "tut_p4_txt": "Type your presentation topic here and click the blue button next to it for the AI to generate everything from scratch. Remember: on the FREE plan, this is locked.",
        "tut_p5_tit": "Step 5: Choosing Images",
        "tut_p5_txt": "After the AI processes your topic, a new window will open automatically. There, you can choose the suggested photos for each slide or check 'Do not use image'. Only after this is the presentation born!",
        "tut_p6_tit": "Step 6: Time Machine",
        "tut_p6_txt": "The app saves your recent generations on your PC. Use this button to recover a file you generated previously without spending your cloud credits.",
        "tut_p7_tit": "Step 7: Ready Formats",
        "tut_p7_txt": "Use this box to apply Ready Formats (Presets). The app will automatically adjust the entire color palette to give you a starting point.",
        "tut_p8_tit": "Step 8: Title Color",
        "tut_p8_txt": "Click here to choose the color that will be applied exclusively to the slide Titles.",
        "tut_p9_tit": "Step 9: Title Font",
        "tut_p9_txt": "Select a native font for the Titles or use the '+' button to add a specific font installed on your PC.",
        "tut_p10_tit": "Step 10: Text Color",
        "tut_p10_txt": "Set the color for the body text and explanatory cards. Everything is independent of the titles!",
        "tut_p11_tit": "Step 11: Text Font",
        "tut_p11_txt": "Just like with titles, choose the font family that will be used for all text content in the presentation.",
        "tut_p12_tit": "Step 12: Cards Background",
        "tut_p12_txt": "The AI can generate cards to separate information. If you want to highlight these boxes with a specific background color, choose here (Button 3).",
        "tut_p13_tit": "Step 13: Slide Background",
        "tut_p13_txt": "Use Button 4 to load an image from your computer that will serve as the texture or background for the entire presentation.",
        "tut_p14_tit": "Step 14: Image Scale",
        "tut_p14_txt": "Check this box to unlock the slider. With it, you can decrease or increase the size of the images on the slides.",
        "tut_p15_tit": "Step 15: Text Scale",
        "tut_p15_txt": "Think the font is small? Check here (Item 5.1) and increase the font proportion of the entire presentation at once.",
        "tut_p16_tit": "Step 16: The Mini-Slide (Preview)",
        "tut_p16_txt": "Look here! All colors, fonts, backgrounds, and scales you alter will be reflected here in real time so you can see how it looks.",
        "tut_p17_tit": "Step 17: Presenter Mode",
        "tut_p17_txt": "Leave checked for the AI to generate a script of what you should say and place it in PowerPoint's notes. You also control the blue sidebar here.",
        "tut_p18_tit": "Step 18: The Grand Finale",
        "tut_p18_txt": "All set and configured? Click here to process all your choices, apply the design, and save your final PPTX file.",
        "tut_p19_tit": "Step 19: Export to PDF",
        "tut_p19_txt": "With the presentation ready and saved, you can use this red button to instantly convert it to PDF with a single click!\n\nDone! The stage is yours."
    }
}